name: Build
on:
  push:
    branches: "**"
  pull_request:
    branches: "**"

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: "Release, gcc",
            os: "ubuntu-latest",
            build-type: "Release",
            cc: "gcc",
            options: "",
          }
          - {
            name: "Release, clang",
            os: "ubuntu-latest",
            build-type: "Release",
            cc: "clang",
            options: "",
          }
          - {
            name: "Debug, gcc",
            os: "ubuntu-latest",
            build-type: "Debug",
            cc: "gcc",
            options: "-D ENABLE_DEBUG=ON",
          }
          - {
            name: "Debug, clang",
            os: "ubuntu-latest",
            build-type: "Debug",
            cc: "clang",
            options: "-D ENABLE_DEBUG=ON",
          }
          - {
            name: "Asan, Ubsan, Lsan",
            os: "ubuntu-latest",
            build-type: "Debug",
            cc: "clang",
            options: "-D CMAKE_C_FLAGS=-fsanitize=address,undefined,leak -D ENABLE_DEBUG=ON",
          }

    steps:
      - uses: actions/checkout@v3

      - name: Configure
        shell: bash
        working-directory: ${{ github.workspace }}
        run: |
          mkdir build
          cd build
          CC=${{ matrix.config.cc }} cmake -DCMAKE_BUILD_TYPE=${{ matrix.config.build-type }} ${{ matrix.config.options }} ..

      - name: Build
        shell: bash
        working-directory: ${{ github.workspace }}/build
        run: |
          export LC_ALL=C.UTF-8
          make

